version: '3.8'
services:
  backend:
    container_name: node_ts
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - '.:/app'
      - /app/node_modules
    networks:
      - trandung
networks:
  trandung: